/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as BecomeVendorRouteImport } from './routes/become-vendor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as KioskSlugRouteImport } from './routes/kiosk.$slug'
import { Route as DashboardCreateKioskRouteImport } from './routes/dashboard.create-kiosk'
import { Route as DashboardEditKioskIdRouteImport } from './routes/dashboard.edit-kiosk.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeVendorRoute = BecomeVendorRouteImport.update({
  id: '/become-vendor',
  path: '/become-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskSlugRoute = KioskSlugRouteImport.update({
  id: '/kiosk/$slug',
  path: '/kiosk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreateKioskRoute = DashboardCreateKioskRouteImport.update({
  id: '/dashboard/create-kiosk',
  path: '/dashboard/create-kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditKioskIdRoute = DashboardEditKioskIdRouteImport.update({
  id: '/dashboard/edit-kiosk/$id',
  path: '/dashboard/edit-kiosk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/create-kiosk': typeof DashboardCreateKioskRoute
  '/kiosk/$slug': typeof KioskSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit-kiosk/$id': typeof DashboardEditKioskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/create-kiosk': typeof DashboardCreateKioskRoute
  '/kiosk/$slug': typeof KioskSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/edit-kiosk/$id': typeof DashboardEditKioskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/create-kiosk': typeof DashboardCreateKioskRoute
  '/kiosk/$slug': typeof KioskSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit-kiosk/$id': typeof DashboardEditKioskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-vendor'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/dashboard/create-kiosk'
    | '/kiosk/$slug'
    | '/product/$handle'
    | '/dashboard/'
    | '/dashboard/edit-kiosk/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-vendor'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/dashboard/create-kiosk'
    | '/kiosk/$slug'
    | '/product/$handle'
    | '/dashboard'
    | '/dashboard/edit-kiosk/$id'
  id:
    | '__root__'
    | '/'
    | '/become-vendor'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/dashboard/create-kiosk'
    | '/kiosk/$slug'
    | '/product/$handle'
    | '/dashboard/'
    | '/dashboard/edit-kiosk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeVendorRoute: typeof BecomeVendorRoute
  DiscoverRoute: typeof DiscoverRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  DashboardCreateKioskRoute: typeof DashboardCreateKioskRoute
  KioskSlugRoute: typeof KioskSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEditKioskIdRoute: typeof DashboardEditKioskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-vendor': {
      id: '/become-vendor'
      path: '/become-vendor'
      fullPath: '/become-vendor'
      preLoaderRoute: typeof BecomeVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/$slug': {
      id: '/kiosk/$slug'
      path: '/kiosk/$slug'
      fullPath: '/kiosk/$slug'
      preLoaderRoute: typeof KioskSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/create-kiosk': {
      id: '/dashboard/create-kiosk'
      path: '/dashboard/create-kiosk'
      fullPath: '/dashboard/create-kiosk'
      preLoaderRoute: typeof DashboardCreateKioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/edit-kiosk/$id': {
      id: '/dashboard/edit-kiosk/$id'
      path: '/dashboard/edit-kiosk/$id'
      fullPath: '/dashboard/edit-kiosk/$id'
      preLoaderRoute: typeof DashboardEditKioskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeVendorRoute: BecomeVendorRoute,
  DiscoverRoute: DiscoverRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  DashboardCreateKioskRoute: DashboardCreateKioskRoute,
  KioskSlugRoute: KioskSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEditKioskIdRoute: DashboardEditKioskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
